# config/packages/scheb_two_factor.yaml

scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
    google:
        enabled: true
    firewall_names:
        - admin
