sylius_twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            custom_styles:
                template: '@VivanWebSolutionSylius2FAPlugin/shop/shared/layout/base/styles.html.twig'
                priority: -100

        'sylius_shop.base#javascripts':
            custom_scripts:
                template: '@VivanWebSolutionSylius2FAPlugin/shop/shared/layout/base/scripts.html.twig'
                priority: -100

        'app_shop.greeting.dynamic':
            content:
                template: '@VivanWebSolutionSylius2FAPlugin/shop/greeting/dynamic/content.html.twig'
                priority: 0
        'app_shop.greeting.static':
            content:
                template: '@VivanWebSolutionSylius2FAPlugin/shop/greeting/static/content.html.twig'
                priority: 0
